version: '3.0'

services:
  song:
    build: .
    container_name: app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      # параметры подключения к БД
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_HOST=db  # используем сетевое имя контейнера
      # параметры подключения к Redis
      - REDIS_HOST=${REDIS_HOST}  # используем сетевое имя контейнера
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      # порт сервиса
      - SERVER_PORT=${SERVER_PORT}